
eureka:
  instance:
    hostname: ${HOSTIP}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    #    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://100.51.0.209:8761/eureka/,http://100.51.1.170:8761/eureka/

spring:
  application:
    name: apigateway-service
  zipkin:
    base-url: http://13.209.136.250:9411   #고정
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes:
        - id: content-service
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/content-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/content-service/(?<segment>.*), /$\{segment}    # /content-service 부분 빼서 포워딩
        - id: execute-service
          uri: lb://EXECUTE-SERVICE
          predicates:
            - Path=/execute-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/execute-service/(?<segment>.*), /$\{segment}    # /execute-service 부분 빼서 포워딩
        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/report-service/**
          filters:
            - RewritePath=/report-service/(?<segment>.*), /$\{segment}    # /execute-service 부분 빼서 포워딩


management:
  endpoints:
    web:
      exposure:
        include: "*"