
server:
  port: ${PORT:8761}

spring:
  application:
    name: discoveryservice

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1 # 디스커버리한테 1초마다 하트비트 전송
    lease-expiration-duration-in-seconds: 2 # 디스커버리는 서비스 등록 해제 하기 전에 마지막 하트비트에서부터 2초 기다림
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://100.51.1.170:8761/eureka/   #peer2
  server:
    enable-self-preservation: false # 자기 보호 모드(네트워크 장애가 발생하여도 서비스 해제를 방지하는 모드) 비활성화
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 3000

logging:
  level:
    com.uplus: DEBUG
    com.netflix: ERROR # INFO #         